config/routes.rb
Rails.application.routes.draw do
  root to: "travels#top"
  get "/schedule", to: "travels#schedule"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def top
  end

  def schedule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!--　ヘッダー　-->
  <header class="header">
    <div class="header_title">
      <%= link_to "我が家の旅行備忘録", root_path%>
    </div>
    <div class="header_menu">
      <div class="menu_icon">
        <%= link_to image_tag("techou_open.png", class: 'icon_image'), schedule_path %>
        <p>Schedule</p>
      </div>
      <div class="menu_icon">
        <%= link_to image_tag("camera_tsukaisute.png", class: 'icon_image'), root_path %>
        <p>Picture</p>
      </div>
      <div class="menu_icon">
        <%= link_to image_tag("video_camera.png", class: 'icon_image'), root_path %>
        <p>Movie</p>
      </div>
      <div class="menu_icon">
        <%= link_to image_tag("travel_suitcase04_green.png", class: 'icon_image'), root_path %>
        <p>Packing</p>
      </div>
      <div class="menu_icon">
        <%= link_to image_tag("bird_aoitori_bluebird.png", class: 'icon_image'), 'https://twitter.com/' %>
        <p>Twitter</p>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/travels/schedule.html.erb
<div class="schedules">
  <div class="schedule">
    <%= image_tag("hyousi.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("ichinichime.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("futukame.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("mikkame.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("yokkame.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("itukame.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("muikame.jpg", class: 'schedule_image') %>
  </div>
  <div class="schedule">
    <%= image_tag("nanokame.jpg", class: 'schedule_image') %>
  </div>
</div>

app/views/travels/top.html.erb
<h1>Travels#top</h1>
<p>Find me in app/views/travels/top.html.erb</p>